### ISSUE TITLE
Unrecognized function or variable 'nmodel'.

### ISSUE THREAD

**Issue by dawson-miller** [JesperLH/prob-tensor-toolbox#4]
There is a function missing titled 'nmodel'. This error prohibits demo_Tucker.m and VB_TUCKER_BTD.m from running.
![tucker_error](https://user-images.githubusercontent.com/82901642/117006932-05216780-acb7-11eb-8d7f-7e32c05dc9de.PNG)

**Comment by JesperLH** [comment]
The nmodel.m comes from the dependency on the N-way toolbox, see http://www.models.life.ku.dk/nwaytoolbox

I will consider if this dependency is strictly necessary or should be replaced by a custom function. For now, I suggest just downloading the N-way toolbox.

**Comment by dawson-miller** [comment]
Thanks
